### ISSUE TITLE
Console window not appearing for latest version

### ISSUE THREAD

**Issue by sh30801** [Yucked/Frostbyte#11]
I cloned the latest version of Concept today, also got IIS and ASP.Net installed. When I launch the program it creates a window w/ localhost but the console window does not appear. Is there another area where info is being logged?

**Comment by Yucked** [comment]
I'm confused. So, it shows a window with localhost but no console window? What kind of window does it create then?

**Comment by renanrcp** [comment]
You need to run the app without the IIS, in the start app options, you select Concept instead IIS Express

**Comment by sh30801** [comment]
Yep that was the issue, appreciate it
