### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by sh30801** [Yucked/Frostbyte#12]
I would like to contribute to this if that's possible. Overall, what's on the bucketlist for things to implement in Concept?

**Comment by Yucked** [comment]
So, the current design is kinda abstract.

- Concept itself is the ws/rest server that handles client ws connections and replies back to HTTP GET requests to get tracks.

- [Theory](https://github.com/Yucked/Theory) is the library that handles all the searching sites for your terms and stuff.

- [Vysn.Voice](https://github.com/Vysn/Voice) is the library that is going to handle all the voice connections.

## `Where each project is at:`
Currently, Concept has an almost finished base. Meaning it handles all ws and rest connections properly.
What's next is defining payload structure similar to Lavalink: Play, Pause, Resume, Stop, Volume, etc.
These payloads will be handled in WS.

Theory on the other hand has a solid implementation of SoundCloud, YouTube, BandCamp and HTTP. What it's waiting for is making sure all the Unit Tests are successful. And, perhaps converting the audio file format to something that can be streamed.

Vysn.Voice is currently at encoding audio with opus. To say the least, it's still unfinished and it will be the main library that handles all the voice stuff.

You can join the Discord server if you'd like. New todo things are popping up every other week or so. But, there are open issues on Theory if you'd like to check them out.

**Comment by sh30801** [comment]
Yeah for sure, I may check that out or start writing payload support for Concept. Where can I find your server invite?

**Comment by Yucked** [comment]
It's in the README.
