### ISSUE TITLE
[ FEATURE REQUEST ] An controller that show you if a source is rate limited

### ISSUE THREAD

**Issue by renanrcp** [Yucked/Frostbyte#15]
With that the user can know if a source is rate limited, (GET/RateLimit/YouTube), and will return a boolean.

Why that feature? If a user has more than 1 instances of Concept he can know the best Concept he will use by the rate limit.

Now we need to discover a magic way to know if a source like YouTube or SoundCloud is rate limited lmao.

**Comment by Yucked** [comment]
Nawe, that seems redundant. SoundCloud won't be ratelimiting and neither will BandCamp. If anything, we either add a global proxy for Frostbyte which changes address after x amount of requests or we just return `SearchResult.SearchError` for sources.

**Comment by renanrcp** [comment]
Sure, I was also wanting something else that is missing, is that when you search and find nothing in some sources it returns SearchResult status instead of NoMatches

**Comment by Yucked** [comment]
What do you mean?

**Comment by renanrcp** [comment]
When you search anything in SoundCloud for example, and the SoundClound don't return anything (empty array "[]") the Theory continues returning SearchResult instead NoMatches.

**Comment by Yucked** [comment]
Good catch. That seems reasonable.
We can also check all other sources for that as well.
